---
- hosts: estudos2
  become: true
  tasks:
          -  name: host conectado!!
             ping:
          
          -  name: Atualizando o apt
             apt: update_cache=yes cache_valid_time=3600
             
             #PHP
          -  name: Instalar o Php
             apt:  name={{item}} state=present
             with_items:
                - php7.4  
                - php7.4-fpm                          
                - php7.4-mysql                          
                - php7.4-common                          
                - php7.4-cli
                - php-common  
                - php7.4-json                          
                - php7.4-opcache                          
                - php7.4-readline                          
                - php7.4-mbstring                          
                - php7.4-xml                          
                - php7.4-gd                          
                - php7.4-curl                      
          
          - name: Removendo o apache2
            apt: name=apache2 state=absent           
            
            #MARIADB 
          - name: Instalando o MariaDB
            apt: name={{item}} state=present
            with_items:
                    - mariadb-server
                    - mariadb-client
                    - python3-mysqldb
                    - python3-mysqldb-dbg
         
          - name: Gerando um novo root password
            command: openssl rand -hex 7 creates=/root/.my.cnf
            register: mysql_new_root_pass

          - name: Removendo usuários anonimo
            mysql_user: name="" state=absent

          - name: Removendo banco de dados de testes
            mysql_db: name=test state=absent

          - name: Upando a senha de root
            mysql_user: name=root host={{item}} password{{mysql_new_root_pass.stdout}}
            with_items:
                    - "{{ ansible_hostname }}"
                    - 127.0.0.1
                    - ::1
                    - localhost
          
          - name: Mostrando a nova senha de root
            ansible.builtin.debug:
                    msg:
                      - " A nova senha do root é {{mysql_new_root_pass.stdout}}"   

          - name: Criando o my.cnf
            template: src=templates/mysql/my.cnf dest=/root/.my.cnf

            #NGINX
          - name: Instalando o ngnix
            apt: name=nginx state=present force=yes update_cache=yes

          - name: Iniciando nginx
            service: name=nginx state=started

          - name: Removendo o arquivo de configurção padrão
            file: path=/etc/nginx/sites-enabled/default state=absent

          - name: Removendo o index padrão
            file: path=/var/www/html/{{item}} state=absent
            with_items:
                    - index.html  
                    - index.nginx-debian.html
                      
          - name: Criando configuração do Nginx
            template: src=templates/nginx/default dest=/etc/nginx/sites-available/estudo
            notify: Reiniciando o Nginx
          

           #WORDPRESS
          - name: Pegando o checksum do wordpress
            uri: url=https://wordpress.org/latest.zip.sha1 return_content=true
            register: wp_checksum

          - name: Baixando o Wordpress ultima versão
            get_url: 
                url: https://wordpress.org/latest.zip 
                dest: /tmp/wordpress.zip 
                checksum: "sha1:{{wp_checksum.content}}"
          
          #CONFIGURANDO A INSTALAÇÃO DO WORDPRESS
          - name: Instalando ferramentas requeridas
            apt: name={{item}} state=present
            with_items:
                    - unzip

          - name: Descompactando o Wordpress
            unarchive:
                    src: /tmp/wordpress.zip 
                    dest: /tmp
                    copy: no
                    creates: /tmp/wordpress/wp-settings.php
          
          - name: Criando pasta do projeto
            file: dest=/var/www/html/estudo  state=directory

          - name: Criando site-avaliable estudo
            file: dest=/etc/nginx/sites-enabled/estudo state=absent

          - name: Criando links
            command: ln -s /etc/nginx/sites-available/estudo /etc/nginx/sites-enabled/
          
          - name: Copiando arquivos para o diretorio wordpress
            command: cp -a /tmp/wordpress/. /var/www/html/estudo creates=/var/www/html/estudo/wp-settings.php
          
          - name: Criando a base de dados wordpress
            mysql_db: name=wordpress state=present

          - name: Criando o usuário wordpress
            mysql_user: name=wordpress host=localhost login_password=Sti@2022 priv=wordpress.*:ALL
            

          - name: Criando a configuração wp-config
            template: src=templates/wordpress/wp-config.php dest=/var/www/html/estudo/wp-config.php


  handlers:
          - name: Reiniciando o Nginx
            service: name=nginx state=restarted

            



